### ISSUE TITLE
MultiTenancyRepository.findById is ignored

### ISSUE THREAD

**Issue by bernardgut** [M-Devloo/Spring-boot-auth0-discriminator-multitenancy#10]
HI @M-Devloo 

Maybe this is more me not understanding properly how this works but basically in the documentation you say:
>When using Spring Data be careful to know which methods of SimpleJpaRepository are using direct fetching (em.find()) and which ones are using (getQuery() -> CriteriaBuilder) as the @Filter is NOT applied for direct fetching!
Luckily the class MultiTenancyRepository already takes care of this problem completely!

Somehow I cannot manage to have my calls to `finById` use the overriden function defined in MultitenancyRepository.

In my case I have:

```
public interface ContractTypeRepository extends JpaRepository<ContractType, Long>,
        JpaSpecificationExecutor<ContractType>, MultiTenant {
}

```

```
public class ContractType extends TenantEntity {
...
}

```

```
public ContractType getContractTypeById(Long contractId) {
    return contractTypeRepository.findById(contractId).orElse(null);
}
```

And, in some controller :
`ContractType contractType = contractService.getContractTypeById(contractTypeId);`

When I use breakpoints, I see that the flow goes through the TenantServiceAspect to apply the filter (OK), but **it doesn't go in the findById() that we defined in MultiTenancyRepository**. Instead I assume it uses the "direct fetching" `findById` that you described above. The one that ignores my filter. 

What am I missing ? How do I enforce the correct execution flow ?

Sorry if this is a stupid question but reading your code, I assumed this was done "automagically" by this `JpaSpecificationExecutor<ContractType>`. But adding or removing this extension to the repository doesn't change anything (it is multitenant for the "complex" queries and non-multitenant for the "direct fetching" ones. I tested this). Not really clear how this works.

Thanks

- Bernard

**Comment by M-Devloo** [comment]
Good evening @bernardgut, the MultitenancyRepository gets autowired by Spring when you define the `@EnableJpaRepositories` annotation that the framework needs to use the MultiTenancyRepository.class as the repository base class. Otherwise it will just use the default SimpleJpaRepository implementation that does direct fetching in the methods: `findById` and `delete`.

Taken from [MultiTenancyApplication.java](https://github.com/M-Devloo/Spring-boot-auth0-discriminator-multitenancy/blob/master/src/main/java/com/github/mdevloo/multi/tenancy/MultiTenancyApplication.java)

```
@SpringBootApplication
@EnableConfigurationProperties
@EnableJpaRepositories(repositoryBaseClass = MultiTenancyRepository.class)
public class MultiTenancyApplication {

  public static void main(final String[] args) {
    SpringApplication.run(MultiTenancyApplication.class, args);
  }
}
```

When running a test that calls the findById method, you can add a breakpoint and you will see that it uses the MultiTenancyRepository class

![image](https://user-images.githubusercontent.com/36577596/131029072-560e175f-ac9f-4075-b4a7-c087f0b391b9.png)

Hope this helps,

Michael

**Comment by M-Devloo** [comment]
Did my comment resolve your question @bernardgut ? :)
